// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Commit struct {
	Sha            string
	AuthorName     string
	AuthorEmail    sql.NullString
	AuthorDate     sql.NullTime
	CommitterName  string
	CommitterEmail sql.NullString
	CommitterDate  sql.NullTime
	Message        string
}

type Embedding struct {
	ID                int64
	CommitSha         string
	Source            string
	Model             string
	Dim               int64
	Vector            []byte
	SyncedToChromemAt sql.NullTime
}
