// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	InsertCommit(ctx context.Context, arg InsertCommitParams) error
	InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error
	ListUnsyncedEmbeddings(ctx context.Context) ([]ListUnsyncedEmbeddingsRow, error)
	MarkEmbeddingSynced(ctx context.Context, arg MarkEmbeddingSyncedParams) error
}

var _ Querier = (*Queries)(nil)
