// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertCommit = `-- name: InsertCommit :exec
INSERT INTO commits (
    sha, author_name, author_email, author_date,
    committer_name, committer_email, committer_date, message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (sha) DO NOTHING
`

type InsertCommitParams struct {
	Sha            string
	AuthorName     string
	AuthorEmail    sql.NullString
	AuthorDate     sql.NullTime
	CommitterName  string
	CommitterEmail sql.NullString
	CommitterDate  sql.NullTime
	Message        string
}

func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertCommit,
		arg.Sha,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.CommitterName,
		arg.CommitterEmail,
		arg.CommitterDate,
		arg.Message,
	)
	return err
}

const insertEmbedding = `-- name: InsertEmbedding :exec
INSERT INTO embeddings (
    commit_sha, source, model, dim, vector
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT (commit_sha, model, source) DO NOTHING
`

type InsertEmbeddingParams struct {
	CommitSha string
	Source    string
	Model     string
	Dim       int64
	Vector    []byte
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, insertEmbedding,
		arg.CommitSha,
		arg.Source,
		arg.Model,
		arg.Dim,
		arg.Vector,
	)
	return err
}
