// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertCommit = `-- name: InsertCommit :exec
INSERT INTO commits (
    sha, author_name, author_email, author_date,
    committer_name, committer_email, committer_date, message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (sha) DO NOTHING
`

type InsertCommitParams struct {
	Sha            string
	AuthorName     string
	AuthorEmail    sql.NullString
	AuthorDate     sql.NullTime
	CommitterName  string
	CommitterEmail sql.NullString
	CommitterDate  sql.NullTime
	Message        string
}

func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertCommit,
		arg.Sha,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.CommitterName,
		arg.CommitterEmail,
		arg.CommitterDate,
		arg.Message,
	)
	return err
}

const insertEmbedding = `-- name: InsertEmbedding :exec
INSERT INTO embeddings (
    commit_sha, source, model, dim, vector
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT (commit_sha, model, source) DO NOTHING
`

type InsertEmbeddingParams struct {
	CommitSha string
	Source    string
	Model     string
	Dim       int64
	Vector    []byte
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, insertEmbedding,
		arg.CommitSha,
		arg.Source,
		arg.Model,
		arg.Dim,
		arg.Vector,
	)
	return err
}

const listUnsyncedEmbeddings = `-- name: ListUnsyncedEmbeddings :many
SELECT commit_sha, source, model, dim, vector
FROM embeddings
WHERE synced_to_chromem_at IS NULL
`

type ListUnsyncedEmbeddingsRow struct {
	CommitSha string
	Source    string
	Model     string
	Dim       int64
	Vector    []byte
}

func (q *Queries) ListUnsyncedEmbeddings(ctx context.Context) ([]ListUnsyncedEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnsyncedEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnsyncedEmbeddingsRow{}
	for rows.Next() {
		var i ListUnsyncedEmbeddingsRow
		if err := rows.Scan(
			&i.CommitSha,
			&i.Source,
			&i.Model,
			&i.Dim,
			&i.Vector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmbeddingSynced = `-- name: MarkEmbeddingSynced :exec
UPDATE embeddings SET synced_to_chromem_at = ?
WHERE commit_sha = ? AND source = ? and model = ?
`

type MarkEmbeddingSyncedParams struct {
	SyncedToChromemAt sql.NullTime
	CommitSha         string
	Source            string
	Model             string
}

func (q *Queries) MarkEmbeddingSynced(ctx context.Context, arg MarkEmbeddingSyncedParams) error {
	_, err := q.db.ExecContext(ctx, markEmbeddingSynced,
		arg.SyncedToChromemAt,
		arg.CommitSha,
		arg.Source,
		arg.Model,
	)
	return err
}
